{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "datasources-backend.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datasources-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "datasources-backend.name" . }}
    creationPolicy: Owner
  data:
    {{- range $k8sKey, $akvKey := .Values.externalSecret.data }}
    - secretKey: {{ $k8sKey }}
      remoteRef:
        key: {{ $akvKey }}
    {{- end }}
{{- end }}
